### PR TITLE
fix(Config): del useless loading config

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
- Delete useless config loading. This module supports CMake macros `AC_ADD_CONFIG_FILE`

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
yes, it used old config method (like v1)

**Comment by BarbzYHOOL** [comment]
but did you test it ? lol

**Comment by Winfidonarleyan** [comment]
This module use two methodd, i delete old

**Comment by BarbzYHOOL** [comment]
ok should be fine, i'll try to use the latest commit soon anyway (if i don't forget)

**Pull request merged**
