### PR TITLE
Fix double cost thanks to Deku

### PR DESCRIPTION
**Pull request by Rochet2**
See this:
https://github.com/azerothcore/mod-transmog/pull/7#discussion_r171092453

### CODE REVIEW

**Comment by Yehonal** [comment]
If has been tested, please merge it

**Comment by Rochet2** [comment]
@Yehonal It looks like none of the teams have access:
https://github.com/orgs/azerothcore/teams/developers/repositories
https://github.com/orgs/azerothcore/teams/developers-classic/repositories
https://github.com/orgs/azerothcore/teams/testers/repositories

Sould they?

**Comment by Yehonal** [comment]
Now you have admin rights here

**Comment by BarbzYHOOL** [comment]
On that matter, why all the repos are "read" while I've put them on "write" ? did you change them yourself yehonal

**Comment by Yehonal** [comment]
Modules must be directly developed by its author and specific devs.

Il 16 Mar 2018 20:23, "Barbz" <notifications@github.com> ha scritto:

**Pull request merged**
