### PR TITLE
feat(Core/Locale): add support GameLocale

### PR DESCRIPTION
**Pull request by Winfidonarleyan**

### CODE REVIEW

**Comment by Helias** [comment]
merge conflicts

**Comment by Winfidonarleyan** [comment]
For this need https://github.com/azerothcore/azerothcore-wotlk/pull/6896 anyway

**Comment by Tony931023** [comment]
@Winfidonarleyan  How is the state of this PR, can you test it to see if it works? It would be very useful for the translations of the modules

**Comment by benjymansy123** [comment]
Should we close this since https://github.com/azerothcore/azerothcore-wotlk/pull/6896 is abandoned?

**Pull request closed without merging**
