### PR TITLE
feat: replace old gossip macros

### PR DESCRIPTION
**Pull request by Stoabrogga**
adapt to this commit:
https://github.com/azerothcore/azerothcore-wotlk/commit/b6cb9247ba96a862ee274c0765004e6d2e66e9e4

Tested in-game and build on Ubuntu 16.04, clang 7

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Should we merge this? why nobody complained?

**Comment by Deku** [comment]
@BarbzYHOOL maybe not everybody is updating to the lastest changes in master, since it breaks most of the modules

**Comment by Stoabrogga** [comment]
@BarbzYHOOL 
Nobody complained because the old preprocessor macros are still present in the core. This PR will switch from using the preprocessor macros to the actual gossip functions, so the module will become incompatible to the core with commits older than https://github.com/azerothcore/azerothcore-wotlk/commit/b6cb9247ba96a862ee274c0765004e6d2e66e9e4.

**Comment by BarbzYHOOL** [comment]
Ok but I think we can merge, it's good

**Pull request merged**
