### PR TITLE
Local languages

### PR DESCRIPTION
**Pull request by microbica**
Transmog now supports multiple languages. The code automatically detects the default language set by each player in their game and uses database columns to retrieve the respective texts in that language. Additionally, we have added text in the code that is already configured to identify the local language and display its corresponding translation. This enhancement has been designed to work with all languages currently available in the game: **koKR**, **frFR**, **deDE**, **zhCN**, **zhTW**, **esES**, **esMX**, **ruRU**. The necessary database alterations are also included in the .sql files.

Please feel free to provide feedback, recommendations, or tips to further improve the code. Any suggestions are welcome!

### CODE REVIEW

**Comment by Helias** [comment]
Thanks for your PR it seems very well done!

**Comment by pangolp** [comment]
@Helias Shall we merge it? Because I think it's something interesting, also, I'm reviewing another bug, and most likely, we may have to resolve a conflict. Although nose.

**Comment by Helias** [comment]
@ZhengPeiRu21 could you review it?

**Comment by pangolp** [comment]
Now I'm trying something, that this module reported to me, and if it works, I'll upload the photo of this pull request. But I have to see if it conflicts with my change, I think not.

**Comment by ZhengPeiRu21** [comment]
Thank you for submitting these changes; these will be a nice quality of life increase for many players. There are some issues with the PR that would best be resolved.

The zhTW translations are incorrect. Many of them are not even Chinese - they are Thai, which will not appear correctly in the zhTW client.

I would suggest using an enum and a switch statement in GetLocaleText rather than passing titleType as a string and using many if-else-if statements.

As much as possible, please try to follow [AzerothCore C++ standards](https://www.azerothcore.org/wiki/cpp-code-standards), such as having braces on the following line.

**Review by ZhengPeiRu21 — CHANGES_REQUESTED** [review]
Thank you for submitting these changes; these will be a nice quality of life increase for many players. There are some issues with the PR that would best be resolved.

The zhTW translations are incorrect. Many of them are not even Chinese - they are Thai, which will not appear correctly in the zhTW client.

I would suggest using an enum and a switch statement in GetLocaleText rather than passing titleType as a string and using many if-else-if statements.

As much as possible, please try to follow [AzerothCore C++ standards](https://www.azerothcore.org/wiki/cpp-code-standards), such as having braces on the following line.

**Comment by microbica** [comment]
I am sorry for the excess of else-if that I had put, apparently I was already very exhausted that day that I did not notice the bad idea of doing it in such a way, however I share the new code, also the translations with the original language

**Comment by ZhengPeiRu21** [comment]
> I am sorry for the excess of else-if that I had put, apparently I was already very exhausted that day that I did not notice the bad idea of doing it in such a way, however I share the new code, also the translations with the original language

Thank you for making those changes. Is there a reason you pass a string to GetLocaleText and use that to look up the textMap rather than just passing the textMap directly?

**Comment by microbica** [comment]
The reason for passing a string to GetLocaleText and using it to look up the textMap instead of passing the textMap directly is to allow for a more flexible and dynamic approach when fetching the localized texts. By using a string parameter, the function can determine which type of equipment slot is being referred to and then use that information to access the appropriate textMap for that slot.

This design choice makes the code more versatile and avoids having to create separate functions or blocks of code for each individual equipment slot. It centralizes the logic and simplifies the codebase, as it handles the localization in a unified manner.

Passing the textMap directly would require having multiple conditional statements or a switch-case structure for each equipment slot, making the code longer and potentially harder to maintain. Instead, the approach with a string parameter abstracts the lookup process and promotes better code reuse and readability.

**Comment by ZhengPeiRu21** [comment]
That makes sense. Thanks for the response.

**Review by ZhengPeiRu21 — APPROVED** [review]

**Pull request merged**
